# Generated by Django 2.0.2 on 2019-06-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_auto_20190604_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
    ]
