# Generated by Django 2.0.2 on 2019-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_storeitem_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='item_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
