# Generated by Django 2.0.2 on 2019-06-06 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_auto_20190606_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='item_id',
            field=models.CharField(default=uuid.UUID('fef00d51-9546-40e8-9844-9bf0786c0cda'), max_length=255, primary_key=True, serialize=False),
        ),
    ]
