# Generated by Django 2.0.2 on 2019-09-22 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0007_auto_20190919_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='item_id',
            field=models.CharField(default=uuid.UUID('784edc1b-d476-49e4-b5df-74cb86db3e82'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
