# Generated by Django 2.0.2 on 2019-06-01 20:39

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_candidate', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.CharField(blank=True, default='20000101', max_length=8, validators=[django.core.validators.RegexValidator(message="Birthdate must be entered in the format: 'YYYY-MM-DD'", regex='^\\+?1?\\d{8}$')])),
                ('formation', models.IntegerField(blank=True, default=0)),
                ('postal_code', models.CharField(blank=True, default='XXXYYY', max_length=6, validators=[django.core.validators.RegexValidator(message='Length has to be 6', regex='^.{6}$')])),
                ('instagram_url', models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator(message='This is not a valid url.')])),
                ('specialities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None)),
                ('schedule', models.IntegerField(blank=True, default=0)),
                ('availability_date', models.CharField(blank=True, default='Now', max_length=30, null=True)),
            ],
        ),
    ]
