# Generated by Django 2.0.2 on 2019-06-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0002_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialities',
        ),
    ]
