# Generated by Django 2.0.2 on 2019-06-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0003_auto_20190601_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
