# Generated by Django 2.0.2 on 2019-06-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0004_auto_20190601_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_candidate',
        ),
    ]
