# Generated by Django 2.0.2 on 2019-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0005_remove_userprofile_is_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
