# Generated by Django 2.0.2 on 2019-06-01 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0006_userprofile_is_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_candidate', serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
