# Generated by Django 2.0.2 on 2019-06-02 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0007_auto_20190601_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_candidate', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
