# Generated by Django 2.0.2 on 2019-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0009_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='commercial_category',
            field=models.IntegerField(default=0),
        ),
    ]
