# Generated by Django 2.0.2 on 2019-06-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0010_auto_20190602_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='commercial_category',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='specialty_demand',
        ),
    ]
