# Generated by Django 2.0.2 on 2019-06-02 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0011_auto_20190602_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='commercial_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='office_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='specialty_demand',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None),
        ),
    ]
