# Generated by Django 2.0.2 on 2019-06-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0013_auto_20190602_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
