# Generated by Django 2.0.2 on 2019-06-02 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0015_auto_20190602_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator(message='This is not a valid url.')]),
        ),
    ]
